server:
  port: 8080
  error:
   include-message: always
   include-binding-errors: always
   include-exception: false
spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username: root
    password: pass
  jpa:
    show-sql: true
    open-in-view: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org: INFO